"""empty message

Revision ID: 93384f4b2e9a
Revises: b40e35cead9a
Create Date: 2025-06-12 16:23:59.066067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93384f4b2e9a'
down_revision = 'b40e35cead9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
